server:
  port: 8081
cupSize: B
age: 18
content: "cupSize: ${cupSize}, age: ${age}"

girl:
    age: 18
    cupSize: B

# 随机int
com:
    gdufs:
        girl:
            number: ${random.int}
        blog:
            name: learning
            title: hello springboot
