
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    data-username: test
    data-password: yygucailiang
    username: test
    password: yygucailiang

  thymeleaf:
    mode: LEGACYHTML5
mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
