
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    data-username: test
    data-password: yygucailiang
    username: test
    password: yygucailiang
  jpa:
    hibernate:
      ddl-auto: validate #validate会验证创建表 不会drop原来的表 create就会
    show-sql: true
  ## Freemarker 配置
  ## 文件配置路径
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

## Mybatis 配置
mybatis:
  typeAliasesPackage: com.gdufs.com.gdufs.freemarker.entity.City
  mapperLocations: classpath:mapper/*.xml

